general:
  overwrite: false
forcefield:
  index: 3
  custom_forcefields:
    1:
      name: amber99sb
      dir: amber99sb.ff
    2:
      name: amber99sb-ildn
      dir: amber99sb-ildn.ff
    3:
      name: amber14sb_OL15
      dir: amber14sb_OL15_cufix_zn.ff
    4:
      name: amber03
      dir: amber03.ff
    5:
      name: amber96
      dir: amber96.ff
    6:
      name: amber94
      dir: amber94.ff
    7:
      name: charmm27
      dir: charmm27.ff
    8:
      name: oplsaa
      dir: oplsaa.ff
water_model:
  index: 1
  custom_water_models:
    1:
      name: tip3p
    2:
      name: tip4p
    3:
      name: spc
    4:
      name: spce
    5:
      name: none
box:
  distance: 1.5
  shape: cubic
  center: true
simulation:
  temperature: 310
  pressure: 1.0
  pH: 7.0
  ligand_charge: 0
  production_time_ns: 5
  dt: 0.002
  equilibration_nvt_time_ps: 500
  equilibration_npt_time_ps: 500
ions:
  neutral: true
  concentration: 0.15
  positive_ion: NA
  negative_ion: CL
constraints:
  algorithm: lincs
  type: h-bonds
  lincs_iter: 1
  lincs_order: 4
energy_minimization:
  integrator: steep
  emtol: 200.0
  emstep: 0.01
  nsteps: 10000
output:
  trajectory_interval_ps: 500
  energy_interval_ps: 10
  log_interval_ps: 10
  compressed_trajectory: true
electrostatics:
  coulombtype: PME
  rcoulomb: 1.0
  pme_order: 4
  fourierspacing: 0.16
vdw:
  rvdw: 1.0
  dispcorr: EnerPres
temperature_coupling:
  tcoupl: V-rescale
  tc_grps:
  - Protein
  - Non-Protein
  tau_t:
  - 0.1
  - 0.1
pressure_coupling:
  pcoupl: C-rescale
  pcoupltype: isotropic
  tau_p: 1.0
  compressibility: 4.5e-05
ligand_forcefield:
  type: gaff
  charge: 0
